export const createFormDB = () => {

}

export const testFormObject = {
    "firstName": "Guillaume",
    "lastName": "Cloutier",
    "email": "guillaume_cloutier123@hotmail.com",
    "phone": "5819960516",
    "Je suis ... Analytique": "10",
    "Je suis ... Audacieux": "0",
    "Je suis ... Amusant": "6",
    "Je suis ... Chaleureux": "4",
    "Je suis ... Organisé": "10",
    "Je suis ... Décidé": "3",
    "Je suis ... Détendu": "9",
    "Je suis ... Sociable": "0",
    "Je suis ... Indépendant": "4",
    "Je suis ... Bavard": "6",
    "Je suis ... Méthodique": "0",
    "Je suis ... Stratégique": "10",
    "Je suis ... Prudent": "4",
    "Je suis ... Droit au but": "6",
    "Je suis ... Bienveillant": "0",
    "Je suis ... Positif": "10",
    "Je fais passer les besoins des autres avant les miens": "10",
    "Je préfère me baser sur des faits concrets que sur des opinions": "0",
    "On dit de moi que je suis une personne divertissante": "6",
    "Je considère important de viser des objectifs ambitieux": "4",
    "Je porte attention aux détails et j'accompli les tâches avec exactitude": "10",
    "Je peux tolérer beaucoup de choses avant de changer une situation désagréable": "0",
    "Je fonce vers l'inconnu avec confiance": "9",
    "J'aime créer des évènements et y impliquer les autres": "6",
    "Je fais preuve de tact": "9",
    "J'aime rencontrer de nouvelles personnes": "10",
    "J'agis de manière confiante": "0",
    "Je vise l'excellence dans tout ce que je fais": "4",
    "Je montre de la compassion pour les autres": "10",
    "Lorsque j'aime vraiment quelque chose, je ne peux pas m'empêcher de le partager avec les autres": "1",
    "Je suis déterminé à atteindre mes objectifs": "8",
    "J'aime les standards élevés": "0",
    "Je crois que tout a un ordre et une suite logique": "6",
    "J'agis de façon spontanée": "4",
    "On dit de moi que je suis une personne directe": "10",
    "Je suis une personne patiente": "0",
    "Je suis motivé par améliorer et perfectionner chaque détail": "7",
    "Je suis motivé par l'opportunité de relever des défis": "2",
    "Je suis motivé par aider et soutenir les autres ": "10",
    "Je suis motivé par créer quelque chose de nouveau": "0",
    "Je m'assure de produire un travail de qualité": "6",
    "J'ai une certaine facilité à diriger les autres": "10",
    "Je crois que les réponses ne doivent pas être précipitées, elles prennent du temps à incuber": "0",
    "J'aime les idées nouvelles qui sortent de l'ordinaire": "4",
    "Lorsque j'ai une décision à prendre ... j'évalue l'impact qu'elle aura sur les autres": "10",
    "Lorsque j'ai une décision à prendre ... je suis mon intuition": "6",
    "Lorsque j'ai une décision à prendre ... je prends le temps d'analyser les données": "3",
    "Lorsque j'ai une décision à prendre ... j'évalue rapidement les options": "0",
    "Dans une équipe ... je veille à la coordination des tâches et je m'assure de la conformité aux règles et procédures": "2",
    "Dans une équipe ... j'utilise mon enthousiasme pour influencer les décisions": "0",
    "Dans une équipe ... je prends des initiatives et des risques pour atteindre les objectifs": "10",
    "Dans une équipe ... j'écoute les préoccupations des autres et je priorise la création d'un environnement harmonieux": "8",
    "Je suis préoccupé... par comment être encore plus efficace": "10",
    "Je suis préoccupé... par comment rendre le moment encore plus intéressant": "7",
    "Je suis préoccupé... par la planification des situations futures": "0",
    "Je suis préoccupé... par ce que pense les autres": "6",
    "Dans une discussion... j'aime qu'on aille directement à l'essentiel": "10",
    "Dans une discussion... je veux qu'on parle avec passion, rien de pire qu'une discussion plate": "0",
    "Dans une discussion... il est important de prendre le temps de s'écouter l'un, l'autre": "6",
    "Dans une discussion... il est important d'être concret, exact et structuré": "4",
    "J'aime guider une équipe vers l'atteinte de grands objectifs avec autorité.": "10",
    "J'aime détendre l'atmosphère en faisant rire les autres dans les moments sérieux.": "6",
    "J'aime inspirer les autres à changer leur façon de penser et à voir de nouvelles possibilités.": "0",
    "J'aime explorer de nouvelles idées et repousser les frontières de mes connaissances.": "4",
    "J'aime relever des défis difficiles et démontrer ma force et mon courage.": "10",
    "J'aime contribuer au bien-être de la communauté en m'assurant que tout le monde se sente inclus et respecté.": "9",
    "J'aime inventer des solutions nouvelles pour résoudre des problèmes complexes.": "0",
    "J'aime offrir un soutien inconditionnel à ceux qui traversent des moments difficiles.": "4",
    "J'aime structurer et organiser les ressources pour garantir l'efficacité.": "8",
    "J'aime défier les conventions pour ouvrir la voie à de nouvelles idées et approches.": "10",
    "J'aime développer des relations profondes et émotionnellement riches avec les autres.": "3",
    "J'aime rechercher la vérité et approfondir mes connaissances sur des sujets élaborés.": "0",
    "J'aime voir le bon côté des choses et adopter une attitude optimiste face à la vie.": "10",
    "J'aime surprendre les autres avec mon humour décalé et mes blagues inattendues.": "6",
    "J'aime être la personne sur qui les autres peuvent compter en cas de besoin.": "0",
    "J'aime sortir de ma zone de confort pour vivre des aventures excitantes.": "7",
    "J'aime guider les autres vers leur propre transformation et croissance.": "0",
    "J'aime exprimer mon affection de manière directe et authentique.": "10",
    "J'aime repousser mes limites pour atteindre mes objectifs ambitieux.": "6",
    "J'aime faire partie d'un groupe où tout le monde est traité sur un pied d'égalité.": "4",
    "J'aime vivre une vie simple et harmonieuse, à l'abri des complications inutiles.": "10",
    "J'aime prendre des risques calculés pour changer les choses autour de moi.": "3",
    "J'aime transformer mes idées en projets concrets qui font une différence.": "0",
    "J'aime partager mes connaissances pour éclairer et guider ceux qui m'entourent.": "6",
    "J'aime découvrir des lieux et des cultures différents pour élargir mes perspectives.": "6",
    "J'aime anticiper les risques et protéger les autres avant qu'ils n'en aient conscience.": "4",
    "J'aime utiliser l'humour pour désamorcer des situations tendues et ramener de la légèreté.": "10",
    "J'aime prendre des décisions importantes pour maintenir l'ordre et la stabilité.": "0",
    "J'aime être une personne reconnu pour surmonter les obstacles.": "7",
    "J'aime être la personne sur qui l'on peut compter dans les moments difficiles pour maintenir l'harmonie collective.": "10",
    "J'aime créer des choses qui n'ont jamais été vues auparavant, en laissant libre cours à mon imagination.": "4",
    "J'aime poser des questions difficiles pour aller au fond des choses.": "0",
    "J'aime vivre des moments intenses de connexion et de partage avec ceux que j'aime.": "6",
    "J'aime bousculer les règles établies pour provoquer des transformations radicales.": "4",
    "J'aime provoquer des changements profonds et durables chez les autres.": "10",
    "J'aime croire en la bonté des autres et espérer des résultats positifs.": "0",
    "Quelle est ta situation professionnelle actuelle et quelles sont tes aspirations à long terme?": "TEST1",
    "Quel a été le plus grand défi que tu as rencontré et comment as-tu réussi à le surmonter ?": "TEST2",
    "Parle moi d'une réussite dont tu es particulièrement fier(ère)?": "TEST3"
}